on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Deploy on Coolify with act
        uses: ./ # Uses an action in the root directory
        id: coolify
        with:
          url: https://baymax.b4you.com.br
          applicationId: cl9j6nvl1005fo9bgi21yh7y6