on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2
      - name: Deploy on Coolify with act
        uses: ./ # Uses an action in the root directory
        id: coolify
        with:
          coolify-url: 
          coolify-app-id: 
          coolify-token: 